# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  
test-unit:
  image: node:8
  stage: test
  script:
    - node -v
    - npm -v
    - npm install
    - npm run unit-test

build-dev:
  image: docker:stable
  only:
    refs:
      - develop
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind 
  stage: build
  script:
    - docker build -t opbd-be .
    - docker -v
    - echo $DOCKER_PASS | docker login --username $DOCKER_LOGIN --password-stdin
    - docker tag opbd-be:latest fusorsoft/opbd-be:develop
    - docker push fusorsoft/opbd-be:develop
    
build-prod:
  image: docker:stable
  only:
    refs:
      - master
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind 
  stage: build
  script:
    - docker build -t opbd-be .
    - docker -v
    - echo $DOCKER_PASS | docker login --username $DOCKER_LOGIN --password-stdin
    - docker tag opbd-be:latest fusorsoft/opbd-be:master
    - docker push fusorsoft/opbd-be:master