# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    
before_script:
  - npm install
  - node -v
  - npm -v

stages:
  - test
  - build
  
test-unit:
  image: node:8
  stage: test
  script:
    - npm run unit-test

lint:
  image: node:8
  stage: test
  script:
    - npm run lint
  

build-dev:
  image: docker:stable
  cache: {}
  before_script:
    - ''
  only:
    refs:
      - develop
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind 
  stage: build
  script:
    - docker build -t opbd-be .
    - docker -v
    - echo $DOCKER_PASS | docker login --username $DOCKER_LOGIN --password-stdin
    - docker tag opbd-be:latest fusorsoft/opbd-be:develop
    - docker push fusorsoft/opbd-be:develop
    
build-prod:
  image: docker:stable
  cache: {}
  before_script:
    - ''
  only:
    refs:
      - master
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind 
  stage: build
  script:
    - docker build -t opbd-be .
    - docker -v
    - echo $DOCKER_PASS | docker login --username $DOCKER_LOGIN --password-stdin
    - docker tag opbd-be:latest fusorsoft/opbd-be:master
    - docker push fusorsoft/opbd-be:master