version: "2"
services:
 be:
  build: .
  env_file:
   - settings.env
  volumes:
   - ./:/app
  ports:
   - "8081:8081"
  links:
   - mongo
 mongo:
  image: mongo
  volumes:
   - ./data:/data
  ports:
   - "27017:27017"
networks:
  default:
    external:
      name: dockernet