version: "2"
services:
 be:
  build: .
  env_file:
   - settings.env
  volumes:
   - ./:/usr/src/app
  ports:
   - "8081:8081"
  links:
   - mongo
 mongo:
  image: 'mongo:3.6.9'
  volumes:
   - ./data:/data/db
  ports:
   - "27017:27017"
networks:
  default:
    external:
      name: dockernet
